version: "3.4"
services:
  web:
    build:
      context: .
      target: develop
    ports:
      - 3000:3000
      - 5858:5858
    volumes:
      - .:/src/app
      - /src/app/node_modules
  static:
    build: .
    ports:
      - 5000:80
